const FRUITS = [
  {
    id: 1,
    name: "Local Mango",
    category: "tropical",
    price: 8.0,
    unit: "each",
    description: "Sweet, juicy mangoes from Ghanaian farms — perfect for smoothies and snacking.",
    image: "images/mango.jpg",
    badge: "Best Seller",
  },
  {
    id: 2,
    name: "Ghana Pineapple",
    category: "tropical",
    price: 12.0,
    unit: "each",
    description: "Golden pineapples from the Eastern Region — naturally sweet and aromatic.",
    image: "images/pineapple.jpg",
    badge: "Popular",
  },
  {
    id: 4,
    name: "Pawpaw (Papaya)",
    category: "tropical",
    price: 10.0,
    unit: "each",
    description: "Soft, orange-fleshed pawpaw — a breakfast staple across Ghana.",
    image: "images/pawpaw.jpg",
    badge: "Fresh",
  },
  {
    id: 5,
    name: "Watermelon",
    category: "melons",
    price: 25.0,
    unit: "each",
    description: "Large, refreshing watermelons — perfect for hot Accra afternoons.",
    image: "images/watermelon.jpg",
    badge: "Seasonal",
  },
  {
    id: 6,
    name: "Local Orange",
    category: "citrus",
    price: 3.0,
    unit: "each",
    description: "Zesty oranges packed with vitamin C — great for fresh juice.",
    image: "images/orange.jpg",
    badge: null,
  },
  {
    id: 7,
    name: "Fresh Coconut",
    category: "tropical",
    price: 5.0,
    unit: "each",
    description: "Young coconuts with sweet water and tender flesh from coastal farms.",
    image: "images/coconut.jpg",
    badge: null,
  },
  {
    id: 8,
    name: "Avocado (Pear)",
    category: "local",
    price: 4.0,
    unit: "each",
    description: "Creamy Ghana pear — rich, buttery, and perfect on bread or salad.",
    image: "images/avocado.webp",
    badge: "Organic",
  },
  {
    id: 9,
    name: "Guava",
    category: "tropical",
    price: 2.5,
    unit: "each",
    description: "Fragrant pink guavas with a tangy-sweet taste loved across West Africa.",
    image: "images/guava.jpg",
    badge: null,
  },
  {
    id: 10,
    name: "Banana",
    category: "tropical",
    price: 5.0,
    unit: "per bunch",
    description: "Sweet bananas from Volta and Ashanti farms — great for children and smoothies.",
    image: "images/banana.jpg",
    badge: null,
  },
  {
    id: 11,
    name: "Passion Fruit",
    category: "tropical",
    price: 6.0,
    unit: "per pack",
    description: "Tart, aromatic passion fruit — ideal for drinks, desserts, and cocktails.",
    image: "images/passion_fruit.jpg",
    badge: "Tropical",
  },
  {
    id: 12,
    name: "Soursop (Aluguntugui)",
    category: "tropical",
    price: 15.0,
    unit: "each",
    description: "Creamy soursop with a unique sweet-tart flavour — a cherished local delicacy.",
    image: "images/soursop.jpg",
    badge: "Local Special",
  },
];

const GALLERY_IMAGES = [
  { src: "images/mango.jpg", title: "Ghana Mangoes" },
  { src: "images/pineapple.jpg", title: "Fresh Pineapple" },
  { src: "images/watermelon.jpg", title: "Watermelon" },
  { src: "images/banana.jpg", title: "Banana Bunch" },
  { src: "https://images.unsplash.com/photo-1488459716781-31db52582fe9?w=600&q=80", title: "Accra Market" },
  { src: "images/coconut.jpg", title: "Coastal Coconuts" },
  { src: "images/avocado.webp", title: "Ghana Pear (Avocado)" },
  { src: "images/fruits.jpg", title: "Mixed Local Fruits" },
];
